test CI/CD

diff --git a/.github/workflows/sample-app-local.yml b/.github/workflows/sample-app-local.yml
--- a/.github/workflows/sample-app-local.yml
+++ b/.github/workflows/sample-app-local.yml
@@ -4,9 +4,6 @@ on:
    branches:
     - main
 
-env:
-  env_1 : hayakawa
-
 jobs:
   build:
     name: build-job
@@ -22,7 +19,6 @@ jobs:
         rmdir /s /q sample-app\x64\Release
         MSBuild sample-app\sample-app.sln /t:rebuild /p:Configuration=Release;Platform=x64
         xcopy sample-app\sample-app\config.ini sample-app\x64\Release
-        echo "ths is env=${{ env.env_1 }}"
 
   unittest:
     name: unittest-job
@@ -34,7 +30,15 @@ jobs:
       run: |
         set PATH=C:\3rdparty\opencv\build\x64\vc15\bin;%PATH%
         cd sample-app\x64\Release
-        .\unittest.exe
+        .\unittest.exe --gtest_output=xml:test_result.xml
+
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+       if: success() || failure()    # run this step even if previous step failed
+       with:
+         name: Google Tests            # Name of the check run which will be created
+         path: test_result.xml    # Path to test results
+         reporter: jest-junit        # Format of test results
 
   # integrationtest:
   #   name: integrationtest-job
